name: Publish Capacitor Plugin to CocoaPods Trunk

on:
  workflow_call:
    secrets:
      COCOAPODS_TRUNK_TOKEN:
        required: true
      CAP_GH_RELEASE_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  publish-ios:
    runs-on: macos-15
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 30
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_26.2.app
      - run: xcrun simctl list > /dev/null
      - run: xcodebuild -downloadPlatform iOS
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }} # explicitly set ref to include commit from `semantic-release`
          token: ${{ secrets.CAP_GH_RELEASE_TOKEN }}
      - name: Install Cocoapods
        run: |
          gem install cocoapods
      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          npm run publish:cocoapod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        working-directory: ./packages/capacitor-plugin
