name: Publish to Cocoapods

on:
  workflow_call:
    secrets:
      COCOAPODS_TRUNK_TOKEN:
        required: true

jobs:
  publish-ios:
    runs-on: macos-15
    timeout-minutes: 30
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_26.2.app
      - run: xcrun simctl list > /dev/null
      - run: xcodebuild -downloadPlatform iOS
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: actions/checkout@v5
      - name: Install Cocoapods
        run: |
          gem install cocoapods
      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          npm run publish:cocoapod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        working-directory: ./packages/capacitor-plugin
